# Generated by Django 4.2.1 on 2023-05-27 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_full', models.CharField(max_length=128, verbose_name='Nazwa firmy:')),
                ('name_short', models.CharField(max_length=128, unique=True, verbose_name='Nazwa skrócona')),
                ('address_street', models.CharField(max_length=128)),
                ('address_postcode', models.CharField(max_length=5)),
                ('address_city', models.CharField(max_length=128)),
                ('address_country', models.CharField(max_length=128)),
                ('vat_number', models.IntegerField()),
                ('email', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=30)),
                ('payment_term', models.IntegerField()),
                ('exchange_rate', models.IntegerField(choices=[(-1, 'Dzień poprzedzający sprzedaż'), (0, 'Dzień poprzedzający wystawienie zlecenia'), (1, 'Dzień załadunku'), (2, 'Dzień poprzedzający dzień załadunku')], default=-1)),
                ('payment_email', models.CharField(max_length=128)),
                ('payment_phone_number', models.CharField(max_length=128, null=True)),
                ('mailing_address_street', models.CharField(max_length=128, null=True)),
                ('mailing_address_postcode', models.CharField(max_length=5, null=True)),
                ('mailing_address_city', models.CharField(max_length=128, null=True)),
                ('mailing_address_country', models.CharField(max_length=128, null=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('position', models.IntegerField(choices=[(0, 'Driver'), (1, 'Freight Forwarder'), (2, 'Senior Freight Forwarder'), (3, 'Owner'), (4, 'Office')])),
                ('start_work_date', models.DateField()),
                ('end_work_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=8)),
                ('driver', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=8)),
                ('truck', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.truck')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('still_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.client')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField()),
                ('order_number', models.CharField(max_length=128)),
                ('order_type', models.IntegerField(choices=[(0, 'EXPORT'), (1, 'IMPORT'), (2, 'PRZEWÓZ KRAJOWY'), (3, 'INNE')])),
                ('pick_up_date', models.DateField()),
                ('pick_up_date_fix', models.IntegerField(null=True)),
                ('pick_up_company', models.CharField(max_length=128)),
                ('pick_up_street', models.CharField(max_length=128)),
                ('pick_up_city', models.CharField(max_length=128)),
                ('pick_up_postcode', models.CharField(max_length=5)),
                ('pick_up_country', models.CharField(max_length=128)),
                ('pick_up_reference', models.CharField(max_length=128, null=True)),
                ('pick_up_comments', models.TextField(null=True)),
                ('delivery_date', models.DateField()),
                ('delivery_date_fix', models.IntegerField(null=True)),
                ('delivery_company', models.CharField(max_length=128)),
                ('delivery_street', models.CharField(max_length=128)),
                ('delivery_city', models.CharField(max_length=128)),
                ('delivery_postcode', models.CharField(max_length=5)),
                ('delivery_country', models.CharField(max_length=128)),
                ('delivery_reference', models.CharField(max_length=128, null=True)),
                ('delivery_comments', models.TextField(null=True)),
                ('pallets_number', models.IntegerField()),
                ('pallets_size', models.IntegerField(choices=[(0, '80x120'), (1, '100x120'), (2, '120X120'), (3, '60x80'), (4, 'inne')])),
                ('ldm', models.FloatField()),
                ('cubic_meters', models.FloatField(null=True)),
                ('weight', models.FloatField()),
                ('client_order_number', models.CharField(max_length=128)),
                ('payment_term', models.IntegerField()),
                ('client_contact_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.person')),
                ('client_vat_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.client')),
                ('truck', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.truck')),
            ],
        ),
    ]
