# Generated by Django 4.2.1 on 2023-06-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_remove_trailer_truck_order_trailer_truck_trailer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(default=1, verbose_name='Stawka (eur)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='pallets_size',
            field=models.CharField(choices=[('80x120', '80x120'), ('100x120', '100x120'), ('120X120', '120X120'), ('60x80', '60x80'), ('inne', 'inne')], max_length=128, verbose_name='Rozmiar palet'),
        ),
    ]
