# Generated by Django 4.2.1 on 2023-06-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_alter_client_vat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address_postcode',
            field=models.CharField(max_length=8, verbose_name='Kod pocztowy'),
        ),
        migrations.AlterField(
            model_name='client',
            name='mailing_address_postcode',
            field=models.CharField(max_length=8, null=True, verbose_name='Kod pocztowy (korespondencja)'),
        ),
    ]
