# Generated by Django 4.2.1 on 2023-06-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_alter_client_address_postcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('Spedycja', 'Spedycja'), ('Księgowość', 'Księgowość'), ('Zarząd', 'Zarząd'), ('Transport', 'Transport')], max_length=128, null=True, verbose_name='Dział'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.IntegerField(choices=[('Driver', 'Driver'), ('Freight Forwarder', 'Freight Forwarder'), ('Senior Freight Forwarder', 'Senior Freight Forwarder'), ('Owner', 'Owner'), ('Office', 'Office')], verbose_name='Stanowisko'),
        ),
    ]
