# Generated by Django 4.2.1 on 2023-06-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_alter_employee_department_alter_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('Spedycja', 'Spedycja'), ('Księgowość', 'Księgowość'), ('Zarząd', 'Zarząd'), ('Transport', 'Transport')], default='-', max_length=128, verbose_name='Dział'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('Driver', 'Driver'), ('Freight Forwarder', 'Freight Forwarder'), ('Senior Freight Forwarder', 'Senior Freight Forwarder'), ('Owner', 'Owner'), ('Office', 'Office')], max_length=128, verbose_name='Stanowisko'),
        ),
    ]
