# Generated by Django 4.2.1 on 2023-06-04 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_alter_employee_department_alter_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client_order_number',
            field=models.CharField(default='-', max_length=128, verbose_name='Numer zlecenia Komtrahenta'),
        ),
        migrations.AlterField(
            model_name='order',
            name='trailer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transport.trailer', verbose_name='Naczepa'),
        ),
        migrations.AlterField(
            model_name='order',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transport.truck', verbose_name='Ciągnik'),
        ),
    ]
