# Generated by Django 4.2.1 on 2023-06-04 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_alter_order_client_order_number_alter_order_trailer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client_vat_number',
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transport.client', verbose_name='Kontrahent'),
        ),
    ]
